### ISSUE TITLE
Give the option to add team members later

### ISSUE THREAD

**Issue by Ruchi-here** [opportunity-hack/quill#10]
It might happen someone wants to add in team or the team leaders wants to add the members, so there should be direct option to do that

**Describe the solution you'd like**
Generate a unique link corresponding to each team

**Additional context**
Here its not obvious how to join a particular team as a team member
![image](https://github.com/user-attachments/assets/00f03177-ffe9-49c5-b154-884cf298212a)

**Comment by gregv** [comment]
Speaking with @Aseem70 and @AndrewHUNGNguyen on this one - the short-term fix for this year is to improve the documentation and UX to make this more obvious - we should create a long-term Issue/Ticket to track how we can do this more effectively

**Comment by Ruchi-here** [comment]
Yeah sure, we can add this thing in our FAQs section

**Comment by gregv** [comment]
Resolved in @Aseem70 's PR linked to this Issue
