### ISSUE TITLE
Update Links to Application Confirmation Form

### ISSUE THREAD

**Issue by AndrewHUNGNguyen** [opportunity-hack/quill#12]
**Describe the bug**
Need to replace the urls for Skill Sheets, Travel Receipts, Liability Waiver, Photo Release, and Code of Conduct in an Admitted Applicant's Confirmation form.

**To Reproduce**
N/A

**Expected behavior**
Needs to have updated links to Opportunity Hack, NOT HackMIT

**Screenshot**
<img width="342" alt="image" src="https://github.com/user-attachments/assets/795f4c15-420c-45e9-bd78-aa13b856a364">

**Comment by gregv** [comment]
Also - since this Issue is link-focused, I created Issue #13 where I noticed some other edits we'd want to make

New ones!
https://www.ohack.dev/hack/code-of-conduct
https://www.ohack.dev/hack/liability-waiver
https://www.ohack.dev/hack/photo-release

**Comment by gregv** [comment]
This was fixed by @AndrewHUNGNguyen in da00e8717e70fff51427efa2062d84a900e538c6
