### ISSUE TITLE
Wrong registration deadline

### ISSUE THREAD

**Issue by Ruchi-here** [opportunity-hack/quill#7]
The date should be close to 12th-13th October not August 13th 2024

**To Reproduce**
![image](https://github.com/user-attachments/assets/4dc08d8e-64e2-42af-9ef4-d9d33863afee)

**Expected behavior**
It should be around 12th-13th oct, please refer the website - https://www.ohack.dev/hack/2024_fall

**Comment by Aseem70** [comment]
Hey Ruchi,

We can change the registration deadline in the admin panel. I have informed Greg and he will change it.

**Comment by gregv** [comment]
@AndrewHUNGNguyen fixed this one
